# config/__init__.py

# Core config
from .config import (
    PLATFORMS,
    BASE_DIR,
    LOG_LEVEL,
    LOG_FILE,
    DATABASE_PATH,
)

# Menu configuration
from .menu_config import (
    MAIN_MENU_OPTIONS,
    POST_MENU_OPTIONS,
    SCHEDULE_MENU_OPTIONS,
    PLATFORM_MENU_OPTIONS,
    ANALYTICS_MENU_OPTIONS,
    SETTINGS_MENU_OPTIONS,
    HELP_MENU_OPTIONS,
    POST_CREATION_STEPS,
    TIMEZONE_OPTIONS,
    TABLE_HEADERS,
    STATUS_ICONS,
    BOX_CHARS,
)

__all__ = [
    # config.py
    "PLATFORMS",
    "BASE_DIR",
    "LOG_LEVEL",
    "LOG_FILE",
    "DATABASE_PATH",

    # menu_config.py
    "MAIN_MENU_OPTIONS",
    "POST_MENU_OPTIONS",
    "SCHEDULE_MENU_OPTIONS",
    "PLATFORM_MENU_OPTIONS",
    "ANALYTICS_MENU_OPTIONS",
    "SETTINGS_MENU_OPTIONS",
    "HELP_MENU_OPTIONS",
    "POST_CREATION_STEPS",
    "TIMEZONE_OPTIONS",
    "TABLE_HEADERS",
    "STATUS_ICONS",
    "BOX_CHARS",
]
